config/routes.rb
Rails.application.routes.draw do
  resources :photos
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    root "fundamental#index" #トップページ
    get "/sitepolicy", to: "fundamental#sitepolicy" #個人情報の扱い
    get "/about_site", to: "fundamental#about_site" #サイト
    get "/display_photo/:id", to: "fundamental#display_photo", as: 'display_photo'
    get "/form", to: "fundamental#form" #問い合わせ
    post '/confirm', to: 'fundamental#confirm'#問い合わせ確認画面
    post '/sended', to: 'fundamental#sended'#問い合わせ完了画面
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact_form.rb
class ContactForm include ActiveModel::Model
 
  attr_accessor :name, :email, :message
 
  validates :name, presence: true
  validates :email, presence: true, format: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
end

app/models/photo.rb
class Photo < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/fundamental_controller.rb
class FundamentalController < ApplicationController
    before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]

    
    def index
     @photos = Photo.all
    end
    
    def sitepolicy
    end    
    
    def about_site
    end
    
    def trade_law
    end 
    
    def display_photo
     @photo = Photo.find(params[:id])
    end    
    
    def form
     @form = ContactForm.new
     render :action => 'form'
    end  
  
    def confirm
     @form = ContactForm.new(form_params)
     if @form.valid?
       render :action => 'confirm'
     else
       render :action => 'form'
     end
    end
 
    def sended
     @form = ContactForm.new(form_params)
     if params[:back]
       render :action => 'form'
     else
       FormMailer.received_email(@form).deliver_now
       render :action => 'sended'
     end
    end
  
    private
    def form_params
     params.require(:contact_form).permit(:name, :email, :message)
    end
  
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
   before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fundamental_helper.rb
module FundamentalHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/fundamental/_footer.html.erb
<footer>
    <div class="footer">
      <div class="container">
          <ul class="footer_menu">
              <li class="navbar-brand　glyphicon" ><%= link_to "このサイトについて","/about_site" %></li>
              <li class="navbar-brand　glyphicon" ><%= link_to "サイト規約","/sitepolicy" %></li>
              <li class="navbar-brand　glyphicon" ><%= link_to "問い合わせメール","/form" %></li>
          </ul>
          <a href="https://twitter.com/test_shere_btn?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @test_shere_btn</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
          <div class="footer-copyright clearfix text-center">
          <p>&copy; Pict-ups</p>
        </div>
      </div>
     </div>  
</footerÏ

app/views/fundamental/_header.html.erb
<nav role="navigation" class="navbar navbar-custom header_fixed">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button data-target="#bs-content-row-navbar-collapse-5" data-toggle="collapse" class="navbar-toggle" type="button">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Pict-ups","/",  :class => "navbar-brand" %>
      </div>
    
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div id="bs-content-row-navbar-collapse-5" class="collapse navbar-collapse">
        <ul class="nav navbar-nav navbar-right">
            <li class="navbar-brand　glyphicon" ><%= link_to "このサイトについて","/about_site" %></li>
            <li class="navbar-brand　glyphicon" ><%= link_to "サイト規約","/sitepolicy" %></li>
            <li class="navbar-brand　glyphicon" ><%= link_to "問い合わせメール","/form" %></li>
            <% if user_signed_in? %>
                 <li class="navbar-brand　glyphicon" ><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
                 <li class="navbar-brand　glyphicon" ><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
            <% else %>
                 <li class="navbar-brand　glyphicon" ><%= link_to 'ログイン', new_user_session_path %> </li>
            <% end %>
            <li class="navbar-brand　glyphicon"> <%= fa_icon("home") %>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
            </li>    
        </ul>
      
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
</div>

app/views/fundamental/_navigation.html.erb
  
 

<div class="col-xs-6 col-sm-3 sidebar-offcanvas" role="navigation">
          <ul class="list-group panel">
            <li class="list-group-item text-center"><i class="glyphicon glyphicon-align-justify"></i>サイトメニュー</li>
            <li>
              
            </li>
            </li>
          </ul>
        </div>

app/views/fundamental/about_site.html.erb
<%= render 'header' %>
<div class="site_text">
<h1>このサイトについて</h1>
<p>気に入った写真を自分で保存できるようにサイトを作りました</p>
<p>楽しんでいただければと思います</p>
</div>
<%= render 'footer' %>

app/views/fundamental/confirm.html.erb
<%= render 'header' %>
<div class="container">
  <%= form_for @form, :url => sended_path do |f| %>
    <div>
      <h2>メッセージ確認</h2>
      <div>
        <strong>名前</strong>
        <p>
          <%= f.hidden_field :name %>
          <%= @form.name %>
        </p>
      </div>
      <div>
        <strong>メールアドレス</strong>
        <p>
          <%= f.hidden_field :email %>
          <%= @form.email %>
        </p>
      </div>
      <div>
        <strong>内容</strong>
        <p>
          <%= f.hidden_field :message %>
          <%= simple_format(@form.message) %>
        </p>
      </div>
        <%= link_to '戻る', '/form', :class => "btn btn-default" %>
        <%= f.submit '内容を送信する', :class => "btn btn-primary"  %>
    </div>
  <% end %>

</div>
<%= render 'footer' %>

app/views/fundamental/display_photo.html.erb
<%= render 'header' %>

 <div class="container-fluid">
    <!--documents-->
      <div class="row">
        <div class="col-xs-12 col-sm-12 content">
          <div class="panel panel-default">
            <div class="panel-heading">
            </div>
            <div class="panel-body ">
              <div class="content-row picture_display">
                <h2 class="content-row-title"><%= @photo.title %></h2>
                <div class="col-sm-12 col-md-6">
                    <div class="thumbnail">
                      <% if @photo.image? %>
                        <%= image_tag(@photo.image.url, :class => "img-rounded ") %> 
                      <% end %>
                    </div>
                </div>
                <a href="https://pict-ups.herokuapp.com/display_photo/<%= @photo.id %>" class="twitter-share-button" data-show-count="false">Tweet</a>
                <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
              </div>
            </div><!-- panel body -->
          </div>
        </div><!-- content -->
      </div>
    </div>
<%= render 'footer' %>

app/views/fundamental/form.html.erb
<%= render 'header' %>

<%= form_for @form, :url => confirm_path do |f| %>
      
    <div class="container">
        <h1 class="">問い合わせ</h1>
        
        <% if @form.errors.any? %>
        <div class="alert alert-danger" role="alert">
          <strong>入力内容にエラーがあります</strong>
          <ul>
            <% @form.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
        <% end %>
        
        <table class="table">
        <tr>
          <th>名前<span class="text-danger">（必須）</span></th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr>
          <th>メールアドレス<span class="text-danger">（必須）</span></th>
          <td><%= f.text_field :email %></td>
        </tr>
        <tr>
          <th>お問い合わせ内容</th>
          <td><%= f.text_area :message %></td>
        </tr>
        </table>
        <%= link_to "戻る", "/", class: 'btn btn-default' %>
        <%= f.submit '内容を確認', class: 'btn btn-primary' %>
       
    </div>    
<% end %>
<%= render 'footer' %>

app/views/fundamental/index.html.erb
<%= render 'header' %>

 <div class="container-fluid">
    <!--documents-->
      <div class="row">
        <div class="col-xs-12 col-sm-12 content">
          <div class="panel panel-primary">
            <div class="panel-heading">
              <h3 class="panel-title"></span>イチオシの1枚！とその他多数……</h3>
            </div>
            <div class="panel-body">
              <div class="content-row">
               <div class="slider">
                  <%= image_tag ('Munch.jpg') %>
               </div>
               
                <h2 class="content-row-title">カテゴリ</h2>
                <div class="row">
                  <% @photos.each do |photo| %>
                    <div class="col-sm-6 col-md-3">
                      <div class="thumbnail">
                        <% if photo.image? %>
                          <%= image_tag(photo.image.thumb.url) %> 
                        <% end %>
                        <div class="caption text-center">
                          <h3><%= photo.title %></h3>
                          <p><%= link_to '見る', display_photo_path(photo), {:class => "btn btn-default", :role => "button"} %></p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                  
                  
                </div><!--row-->
              </div><!--content-row-->
            </div><!-- panel body -->
          </div><!--panel panel-default-->
        </div><!-- content -->
      </div><!--row row-offcanvas row-offcanvas-left-->
    </div><!--container-->
<%= render 'footer' %>

app/views/fundamental/sended.html.erb
<%= render 'header' %>
<div class="container">
  <h2>メッセージ送信完了</h2>
  <p>
    メッセージをいただきありがとうございました。
  </p>
  <p><%= link_to '戻る', '/', :class => "btn btn-default btn-xl", :method => :get %></p>
</div>
<%= render 'footer' %>

app/views/fundamental/show.html.erb
<%= render 'header' %>

 <div class="container-fluid">
    <!--documents-->
      <div class="row row-offcanvas row-offcanvas-left">
      <%= render 'navigation' %>  
        <div class="col-xs-12 col-sm-9 content">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title"><a href="javascript:void(0);" class="toggle-sidebar"><span class="fa fa-angle-double-left" data-toggle="offcanvas" title="Maximize Panel"></span></a> メニュー開閉</h3>
            </div>
            <div class="panel-body">
              <div class="content-row">
               
                <h2 class="content-row-title">詳細ページ</h2>
                <div class="col-sm-12 col-md-6">
                    <div class="thumbnail">
                      <img class="img-rounded" src="dist/img/thumbnail-1.jpg">
                      <div class="caption text-center">
                        <h3>写真</h3>
                        <p>カテゴリの簡単な説明</p>
                      </div>
                    </div>
                </div>
              </div>
            </div><!-- panel body -->
          </div>
        </div><!-- content -->
      </div>
    </div>
<%= render 'footer' %>

app/views/fundamental/sitepolicy.html.erb
<%= render 'header' %>
<center><div class="container site_text">
    <h1 class=""><center>利用規約</center></h1>
    <p>この利用規約（以下、「本規約」といいます。）は、pict-ups（以下、「当サイト」といいます。）がウェブサイト、アプリなどにおいて提供するサービス（以下、「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下、「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。</p>
    <p><strong>第1条（適用）</strong><br />
    本規約は、ユーザーと当サイトとの間の本サービスの利用に関わる一切の関係に適用されるものとします。</p>
    <p><strong>第2条（利用登録）</strong><br />
    １．登録希望者が当サイトの定める方法によって利用登録を申請し、当サイトがこれを承認することによって、利用登録が完了するものとします。<br />
    ２．当サイトは、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。<br />
    （1）利用登録の申請に際して虚偽の事項を届け出た場合<br />
    （2）本規約に違反したことがある者からの申請である場合<br />
    （3）その他、当サイトが利用登録を相当でないと判断した場合</p>
    <p><strong>第3条（禁止事項）</strong><br />
    ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。<br />
    （1）法令または公序良俗に違反する行為<br />
    （2）犯罪行為に関連する行為<br />
    （3）当サイトのサーバーまたはネットワークの機能を破壊したり、妨害したりする行為<br />
    （4）当サイトのサービスの運営を妨害するおそれのある行為<br />
    （5）他のユーザーに関する個人情報等を収集または蓄積する行為<br />
    （6）他のユーザーに成りすます行為<br />
    （7）当サイトのサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為<br />
    （8）その他、当社が不適切と判断する行為</p>
    <p><strong>第4条（本サービスの提供の停止等）</strong><br />
    １．当サイトは、以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。<br />
    （1）本サービスにかかるコンピュータシステムの保守点検または更新を行う場合<br />
    （2）地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合<br />
    （3）コンピュータまたは通信回線等が事故により停止した場合<br />
    （4）その他、当サイトが本サービスの提供が困難と判断した場合<br />
    ２．当サイトは、本サービスの提供の停止または中断により、ユーザーまたは第三者が被ったいかなる不利益または損害について、理由を問わず一切の責任を負わないものとします。</p>
    <p><strong>第5条（利用制限および登録抹消）</strong><br />
    １．当サイトは、以下の場合には、事前の通知なく、ユーザーに対して、本サービスの全部もしくは一部の利用を制限できるものとします。<br />
    （1）本規約のいずれかの条項に違反した場合<br />
    （2）その他、当サイトが本サービスの利用を適当でないと判断した場合<br />
    ２．当サイトは、本条に基づき当社が行った行為によりユーザーに生じた損害について、一切の責任を負いません。</p>
    <p><strong>第6条（免責事項）</strong><br />
    １．当サイトの損害賠償債務は、当サイトの故意または重過失によらない場合には免責されるものとします。<br />
    ２．当サイトは、何らかの理由によって責任を負う場合にも、通常生じうる損害の範囲内においてのみ賠償の責任を負うものとします。<br />
    ３．当サイトは、本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。</p>
    <p><strong>第7条（サービス内容の変更等）</strong><br />
    当サイトは、ホームページなどに告知することによって、ユーザーの承諾なく、本サービスの内容を変更し、または、本サービスの提供を中止することができるものとします。これによってユーザーに生じた損害について、当社は第8条1項以外の場合は、一切の責任を負いません。</p>
    <p><strong>第8条（利用規約の変更）</strong><br />
    当サイトは、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができ、本規約を変更し、ホームページなどでその旨を告知した時点で、ユーザーは本規約を承諾したものとします。</p>
    <p><strong>第9条（通知または連絡）</strong><br />
    ユーザーと当サイトとの間の通知または連絡は、当サイトの定める方法によって行うものとします。</p>
    <p><strong>第10条（権利義務の譲渡の禁止）</strong><br />
    ユーザーは、当サイトの書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。</p>
    <p><strong>第11条（準拠法・裁判管轄）</strong><br />
    １．本規約の解釈にあたっては、日本法を準拠法とします。<br />
    ２．本サービスに関して紛争が生じた場合には、東京地方裁判所を第一審の専属的合意管轄裁判所とします。</p>
    <p>以　上</p>


    <p>平成29年1月1日　策定（公開日を記載）</p>
    <p>平成29年1月1日　改訂（更新日を記載）</p>
</div>
</center>
<%= render 'footer' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Pict-ups</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag('favicon.ico') %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- site css -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,300,600,800,700,400italic,600italic,700italic,800italic,300italic" rel="stylesheet" type="text/css">
    <!-- <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'> -->
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick-theme.css"/>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    

  </head>
  

  <body>
    <div class="container-fluid">
    <%= yield %>
    </div>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%=form.label :image,"ユーザー画像1" %>
    <%= form.file_field :image %> 
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.title %></td>
        <td>
          <% if photo.image? %>
            <%= image_tag(photo.image.url) %> 
          <% end %>
        </td>
        
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo.title %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>